# Generated by Django 6.0 on 2026-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('direction', models.URLField()),
            ],
        ),
    ]
