# Generated by Django 6.0 on 2026-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
